### ISSUE TITLE
Horizontal Scroll

### ISSUE THREAD

**Issue by krish-ram** [joelmukuthu/angular-snapscroll#7] opened 2015-08-21 13:45 UTC
joel,
the changes arent responsive i believe. I am not able to view demo in mobile

**Comment by joelmukuthu** [comment] 2015-08-25 08:42
Hi!
Sorry for the late response. Could you tell a little bit more about what the problem is? I'm not able to replicate any issues on mobile myself.

**Comment by joelmukuthu** [comment] 2015-11-16 14:57
Closing this, couldn't reproduce.

**Closed as completed by joelmukuthu** 2015-11-16 14:57 UTC
