### ISSUE TITLE
Scrolls twice on trackpad touch.

### ISSUE THREAD

**Issue by phedinkus** [joelmukuthu/angular-snapscroll#1] opened 2015-04-03 21:19 UTC
I'm noticing on your demo site the trackpad swipe causes the page to jump 2 slides instead of one. Is that a known issue? I haven't dug into the cause yet...

**Comment by joelmukuthu** [comment] 2015-04-03 21:59
Yeah that's a known issue (that I should document). It happens if the trackpad's sensitivity is so high that the scroll event is triggered after the page has snapped to the first slide, thereby initiating a second scroll event.
One way to evade the issue is to increase the `snap-duration`, so the snap animations run for a longer duration, but it isn't a foolproof solution

**Comment by phedinkus** [comment] 2015-04-06 20:26
Thanks for the info and adding it to the docs. I appreciate all the work you've done on this. Thanks!!

**Comment by joelmukuthu** [comment] 2015-04-06 21:05
No worries! Closing this then :)

**Closed as completed by joelmukuthu** 2015-04-06 21:05 UTC
